# docs/REQUIREMENTS.yaml
# Single Source of Truth for System Requirements
# Compliance: ISO/IEC/IEEE 15288:2015 (Technical Processes)

requirements:
  # --- UI/UX Requirements ---
  - id: REQ-UI-001
    category: Functional
    title: Global Navigation
    description: The system shall provide a responsive navigation bar accessible on all viewports.

  - id: REQ-UI-002
    category: Functional
    title: Pricing Display
    description: The system shall allow users to toggle between Monthly and Yearly pricing intervals.

  - id: REQ-UI-003
    category: Functional
    title: Contact Form
    description: The system shall validate user input (Name, Email, Message) before submission.

  # --- Security Requirements ---
  - id: REQ-SEC-001
    category: Security
    title: Input Sanitization
    description: All user inputs must be sanitized to prevent XSS attacks.

  - id: REQ-SEC-002
    category: Security
    title: API Authentication
    description: All Storyblok API calls must use the correct token (Draft/Public) based on environment.

  # --- Performance Requirements ---
  - id: REQ-PERF-001
    category: Performance
    title: Image Optimization
    description: All images above the fold must utilize eager loading and appropriate fetch priority.

  - id: REQ-PERF-002
    category: Performance
    title: Deferred Rendering
    description: Expensive computational components must be deferred via Server Islands to prevent main-thread blocking.
    